### ISSUE TITLE
Setup CI with GitHub Actions

### ISSUE THREAD

**Issue by liveh2o** [liveh2o/spectacles#33]
Setup [Github Actions](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby) to run tests and linting, and update the repo to require passing CI to merge pull requests.

**Comment by skunkworker** [comment]
@liveh2o I'll take this on, but I might need some permissions to add it to the repository.

**Comment by liveh2o** [comment]
Closed by #32, #37.
